### ISSUE TITLE
unsetOidcAuth method not clearing tokens properly

### ISSUE THREAD

**Issue by SOFSPEEL** [perarnborg/vuex-oidc#1]
In file https://github.com/perarnborg/vuex-oidc/blob/2724bfeffc6988bce991a49a1b04a28fc1ce4c10/src/store/create-store-module.js

`
unsetOidcAuth (state) {
state.token = null
state.token = null
}
`

Should be changed to:
`
unsetOidcAuth (state) {
state.id_token = null
state.access_token = null
}
`

**Comment by perarnborg** [comment]
@SOFSPEEL Cheers, this will be fixed within short!

**Comment by perarnborg** [comment]
Fixed in version 1.5.4
