### ISSUE TITLE
Vue-CLI3 IE11 issue

### ISSUE THREAD

**Issue by SoroTrestal** [perarnborg/vuex-oidc#10]
Hello when I start a new project with Vue-CLI3, my app does not work in IE11.

I tried setting up your sample project and this also does not work in IE11 (blank page).

![image](https://user-images.githubusercontent.com/22880426/47281315-c0db8980-d5da-11e8-8b69-efa753fb88c7.png)

Regards

**Comment by perarnborg** [comment]
@SoroTrestal This should be resolved in v1.8.0, please update and test again.

A note on this subject: The plugin uses Object.assign and Promise, and does not ship with any polyfills.

I am considering to stop using Object.assign (will probably do so within short), but since vuex already requires Promise I will be keeping Promise.

**Comment by SoroTrestal** [comment]
@perarnborg great thank you, I have tested it and at first a received a different error (but this was due the missing of the polyfills you mentioned)

![image](https://user-images.githubusercontent.com/22880426/47301949-84328100-d620-11e8-98a5-f6ab544c53c1.png)

After adding the code in created event of my App (I think these are ones you are using):

`var o = Object.assign({}, "defaultOidcConfig", "oidcSettings");
console.log("object", o);
var arr = ["test"];
console.log(arr.find);
if ("".startsWith) {
}
console.log(Array.from('foo'));`

Vue CLI detects the need for polyfills and tries to add them.
After this everything just works.

Normally you would be able to add the option to the vue.config.js (transpileDependencies: ['vuex-oidc'])
But when I try to do so I receive a compile error in Webpack. 

I think its related to this issue: [https://github.com/vuejs/vue-cli/issues/2637#issuecomment-425441262](url)

**Comment by perarnborg** [comment]
OK!

I think it is a better option for me to ship transpiled code as long as vue and vuex does so. 

I will keep the Promise prerequisite since vuex already has it, but will refactor so Object.assign is not required. 

I’ll keep this issue open until that work is done.

**Comment by perarnborg** [comment]
Object.assign is not required in v1.9.3
