### ISSUE TITLE
Unable to set the value of OidcSettings from Service

### ISSUE THREAD

**Issue by sauravbhadani** [perarnborg/vuex-oidc#100]
Right now with the example provide of vuex-oidc,  OidcSettings is a constant values. I am updating the value of authority, clientId and redirectUri from another API to the constant file but it is not picking the updated value. Is there any way we can update the value before calling the oidc module.

**Comment by perarnborg** [comment]
I think a way to do this would be to create the oidc store module dynamically, as I have suggested in #64. 

A post on how to create modules dynamically: https://alligator.io/vuejs/vuex-dynamic-modules/

I have not tried this myself though.

**Comment by esune** [comment]
This example may help: configurations are fetched by a config service and returned as promises. Once all promises required to initialize the web application are fulfilled, the Vue app is instantiated.

See:
 - [config service](https://github.com/bcgov/issuer-kit/blob/master/issuer-admin/src/services/config/index.ts)
 - [app main](https://github.com/bcgov/issuer-kit/blob/master/issuer-admin/src/main.ts#L16-L35)

**Comment by perarnborg** [comment]
Thanks @esune for providing an example! This looks lika a reasonable approach to me!
