### ISSUE TITLE
[Improvement] [Wiki] - Use standard response_type

### ISSUE THREAD

**Issue by coolhome** [perarnborg/vuex-oidc#11]
I think the oidc settings in the wiki should contain a standard `response_type`. It can be confusing to new people to OIDC

Example:
Going from this:
```js
  response_type: 'openid profile email api1',
```

To something like this:
```js
  response_type: 'id_token token',
```

Great project btw, love how easy it to integrate into existing applications.

**Comment by perarnborg** [comment]
Good point! wiki is updated!
