### ISSUE TITLE
authenticateOidcSilent no longer returns a promise

### ISSUE THREAD

**Issue by GordonBlahut** [perarnborg/vuex-oidc#112]
https://github.com/perarnborg/vuex-oidc/blob/30c0a1b30a9ab4183b2266c99933d0ea86b78c04/src/store/create-store-module.js#L239-L241

Shouldn't the call to the inner `authenticateOidcSilent` be returned here? It's no longer possible to await the promise.

**Comment by perarnborg** [comment]
Indeed it should! Thank you, fixed as of v3.7.1
