### ISSUE TITLE
getOidcUser wrong return type (TypeScript)

### ISSUE THREAD

**Issue by GordonBlahut** [perarnborg/vuex-oidc#113]
https://github.com/perarnborg/vuex-oidc/blob/30c0a1b30a9ab4183b2266c99933d0ea86b78c04/index.d.ts#L120

`getOidcUser: () => () => Promise<User>; ` should be `getOidcUser: () => Promise<User>;`

**Comment by perarnborg** [comment]
Thank you for pointing this out! Fixed as of v3.7.1
