### ISSUE TITLE
Unable to catch event when SilentTokenRenew fails because of IdSrv session ended.

### ISSUE THREAD

**Issue by apavelm** [perarnborg/vuex-oidc#118]
For Single-Page Application doesn't matter if IdSrv session is closed if SPA has a bearer token to communicate with API. But this fact makes impossible to renew token.

I need to remove all auth data in case if on silent token renew figured out that session was closed/invalid.

PR #117

**Comment by apavelm** [comment]
@perarnborg It would be very nice if you could add an option to signOut automatically in case in SilentTokenRenew failed or session became invalid.

**Comment by perarnborg** [comment]
I will look at this (and #117) within the next few days!

**Comment by perarnborg** [comment]
As of v3.9.0 vuexOidcProcessSilentSignInCallback returns a promise that can be caught.

Regarding the request for having an option to sign out automatically: Different implementations have very different behaviours – if they want to sign out the user or not, but also what signing out the user means (in app or at provider, maybe redirecting the user somewhere like public front page or sign in page...). Therefor I would be more comfortable in letting the implementations perform these actions. Hopefully the change where the function returns a promise will enable this!
