### ISSUE TITLE
[Feature Request] [Minor Improvement] Typescript Typings

### ISSUE THREAD

**Issue by coolhome** [perarnborg/vuex-oidc#12]
I personally would benefit from having typescript type definitions for `vuex-oidc`. 

If I ever get around to making it I will submit a PR 👍

**Comment by perarnborg** [comment]
Thanks for the input! I am not a TypeScript user so I will probably not get around to doing this any time soon, but a PR would be welcome!

**Comment by perarnborg** [comment]
Published in v3.5 .0
