### ISSUE TITLE
vuexOidcSignOut to be exposed

### ISSUE THREAD

**Issue by apavelm** [perarnborg/vuex-oidc#126]
This is discussable. And could be considered as a feature request.

Normally, page for silent token-renewal is a lightweight (I believe this is good) and not connected to main Vue application.
In other words it looks like 
![image](https://user-images.githubusercontent.com/6442445/92063614-e5136e80-edde-11ea-8d28-e9176f767c8e.png)

For some use-cases user needs to do a signout when catching an error. 
Maybe this is a good point to expose a method for a signout (or redirect to logout page)?

**Comment by perarnborg** [comment]
It could possibly be a good idea to expose the signout triggers, although I am not certain and in this case it would not really work.

First of all as far as I can see you cannot count on the fact that `siginSilentCallback` (that ´vuexProccessSilentSigninCallback´ returns) gets rejected when the signin fails – see comment in #125 .

And secondly this code runs in an iframe, so this is not where you would want to redirect the user to the provider, you want to do that in the main window. Posting an event up to the parent window could be an option, but I think a better way forward would be to enable cathing the failed signin inside the vue app, which I hope to do shortly.

**Comment by perarnborg** [comment]
Closing this since it is now possible to catch errors on silent signins.
