### ISSUE TITLE
Stalled GET connect/userinfo Question

### ISSUE THREAD

**Issue by glennsills** [perarnborg/vuex-oidc#127]
We are seeing an interesting issue that happens when we deploy our application to different kubernetes clusters.

The login process (against identity server4) works fine in most cases, but in some, the call to connect/userinfo is cancelled in the browser. The preflight Origin request returns a 204 in every case (when it works and when it doesn't work). When it doesn't work the status of the GET is described in different ways on different browsers.  Chromium Edge and Chrome described the call as "Stalled". Firefox describes the call as "Blocked". Of course, tracing through the NGINX logs and the Identity Server logs make it plain that we it doesn't work not HTTP GET request is be dispatched from the browser.

Has anyone else see this sort of problem.

**Comment by coolhome** [comment]
This is definitely not related to this project. I think what you are experiencing is CORS and the browser preventing the `GET` requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

**Comment by glennsills** [comment]
I agree but I was a bit desperate.
