### ISSUE TITLE
[Bug] Store being namespace causes 'unknown action type: oidcCheckAccess'

### ISSUE THREAD

**Issue by coolhome** [perarnborg/vuex-oidc#13]
With the store being namespaced like:

```ts
import Vue from 'vue';
import Vuex from 'vuex';
import { oidcSettings } from '@/config/oidcSettings';
import { vuexOidcCreateStoreModule } from 'vuex-oidc';

Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    oidcStore: vuexOidcCreateStoreModule(oidcSettings, { namespaced: true }),
  },
  state: {

  },
  mutations: {

  },
  actions: {

  },
});
```

The router middleware will fail to properly dispatch `oidcCheckAccess` from https://github.com/perarnborg/vuex-oidc/blob/master/src/router/create-router-middleware.js#L3 because the store is namespaced. In this example, if I dispatch `oidcStore/oidcCheckAccess` or turn off namespaced then the library works perfectly! When namespaced is enabled, I would assume all dispatches are invalid.

**Comment by perarnborg** [comment]
@coolhome Thank you for testing! I have completely overseen this!

As of v1.9.1 you can pass a second argument to vuexOidcCreateRouterMiddleware when setting up the router with the namespace string. 

See docs in https://github.com/perarnborg/vuex-oidc/wiki#4-setup-vue-router

(Your link to the source code also points to where the change is made)

**Comment by perarnborg** [comment]
@coolhome I am sorry, that should be v1.9.2

**Comment by coolhome** [comment]
@perarnborg Thanks for fixing this. I had the same idea for how to pass the namespace in.

**Comment by perarnborg** [comment]
Awesome, thanks for helping!
