### ISSUE TITLE
Where is the token stored?

### ISSUE THREAD

**Issue by rodrigocvb** [perarnborg/vuex-oidc#131]
As far as I know, Vuex stores data in memory. Does that mean that vuex-oidc should be saving the access token in memory too once it's vuex-based? Because I run the [example](https://github.com/perarnborg/vuex-oidc-example) and I can see the token in localStorage. Could anyone clarify this please?

**Comment by Khaos66** [comment]
I believe the token is not persisted anywhere by this library. The user is reauthenticated every time he visits the page. 
But the authentication provider can cache the login in his domain. Mostly as cookies, I guess. So he will return a valid token without another login.

I can be wrong, but this is what I found out. Hope it helps.

Also, if you really want to make the oidc store persistend, then you can try the [vuex-persist](https://github.com/championswimmer/vuex-persist) module.

**Comment by perarnborg** [comment]
@rodrigocvb vuex-oidc only stores the tokens in memory, unless you configure your vuex store to be persisted like @Khaos66 mentions.

The oidc-client library that vuex-oidc uses uses localStorage (or sessionStorage, depending on your setup) to keep track of nounces and states in the authentication process. You will see something like 

```
{"id":"yyy","created":1600059688,"nonce":"zzz","authority":"https://xxx.xxx","client_id":"xxx"}
```
The actual id and access tokens are not stored in the browser localstorage if I am not mistaken.

**Comment by larzon83** [comment]
Tokens are stored in localStorage or sessionStorage:

<img width="587" alt="tokens" src="https://user-images.githubusercontent.com/23213583/93527473-37a16e80-f939-11ea-9656-076acf52c42c.png">

**Comment by rodrigocvb** [comment]
Thanks for the responses. I see the same as @larzon83. My access token appears in localStorage. But I'd not like to store the token in localStorage or sessionStorage. I'd rather store it in memory, by using InMemoryWebStorage, as mentioned in this [oidc-client's issue](https://github.com/IdentityModel/oidc-client-js/issues/888). Is that possible?

**Comment by perarnborg** [comment]
Sorry for this late reply. You should be able to set the userStore in `oidc-client` just like if you would use that library directly. You would pass it inside the first settings argument of `vuexOidcCreateStoreModule`

```
import { InMemoryWebStorage } from 'oidc-client'

vuexOidcCreateStoreModule(
      {
        ...oidcSettings,
        userStore: new InMemoryWebStorage()
      },
}

```
