### ISSUE TITLE
Oidc-client is set as both peer and dev dependency

### ISSUE THREAD

**Issue by droid001** [perarnborg/vuex-oidc#140]
A dependency error is thrown when installing the package :
```This dependency was not found:
* oidc-client in ./node_modules/vuex-oidc/dist/vuex-oidc.esm.js
To install it, you can run: npm install --save oidc-client```
Looks like the setting oidc-client as a peer dependency is redundant as it exists already as a dev-dependency?

**Comment by perarnborg** [comment]
Thanks for pointing this out! Removed the redundant dev dep in https://github.com/perarnborg/vuex-oidc/commit/3a49a7594c7e9f2ceefb5eecb35cc384f8801a02

To be published.

**Comment by perarnborg** [comment]
There was some confusion here. The reason it is a dev dep is so that the unit tests (that need oidc-client) can run on Travis! So I took back the dev dep, but with the same version as the peer dep.
