### ISSUE TITLE
How to do single sign-on without refresh

### ISSUE THREAD

**Issue by tianqinqin** [perarnborg/vuex-oidc#146]
The requirement is to call the back end to get the relevant token after logging in and then jump to the front end. The front end can get the relevant token through the URL, so how can the front end use this token to achieve logon without refreshing

Get the access_Token from the URL and then hold it and do a single sign-on with the access_Token

Can anyone help me

**Comment by perarnborg** [comment]
I am not sure I understand you completely. When you say you want the front end to achieve logon without refreshing – what exactly do you mean?

**Comment by tianqinqin** [comment]
I get access_token through the URL returned by the back end, for example, the return message is`{id_token:'***',access_token:'***',token_type:Bearer,expires_in:86400,scope:'***',state:'***',session_state:'**'}`,I took one of them` {
          access_token: '***',
          token_type: '***',
          id_token:'***',
          scope: '***',
          session_state: '***'
        }`,To make up[oidc.user:***:***],And then put it in cookies, is that right? Is that how to implement SSO? If not, what's missing? Or does Vuex-OIDC offer a corresponding method?

**Comment by tianqinqin** [comment]
> 我不确定我是否完全了解您。当您说要前端实现登录而不刷新时，这是什么意思？


I get access_token through the URL returned by the back end, for example, the return message is`{id_token:'***',access_token:'***',token_type:Bearer,expires_in:86400,scope:'***',state:'***',session_state:'**'}`,I took one of them` {
          access_token: '***',
          token_type: '***',
          id_token:'***',
          scope: '***',
          session_state: '***'
        }`,To make up[oidc.user:***:***],And then put it in cookies, is that right? Is that how to implement SSO? If not, what's missing? Or does Vuex-OIDC offer a corresponding method?

**Comment by tianqinqin** [comment]
> I am not sure I understand you completely. When you say you want the front end to achieve logon without refreshing – what exactly do you mean?

I get access_token through the URL returned by the back end, for example, the return message is{id_token:'***',access_token:'***',token_type:Bearer,expires_in:86400,scope:'***',state:'***',session_state:'**'},I took one of them { access_token: '***', token_type: '***', id_token:'***', scope: '***', session_state: '***' },To make up[oidc.user::],And then put it in cookies, is that right? Is that how to implement SSO? If not, what's missing? Or does Vuex-OIDC offer a corresponding method?
