### ISSUE TITLE
Missing property automaticSilentSignin in VuexOidcClientSettings

### ISSUE THREAD

**Issue by martinussuherman** [perarnborg/vuex-oidc#157]
When developing with typescript, I got error when reading VuexOidcClientSettings because the property automaticSilentSignin is missing from definition. I can create PR for this if you want to. It's just a one liner:
```automaticSilentSignin?: boolean```

Regards, 

Martinus

**Comment by perarnborg** [comment]
Ah, good catch! If you open a PR I will merge it and publish.

If you do not I will get around to it in the next few days! :)

**Comment by martinussuherman** [comment]
@perarnborg I'll make the PR. Thanks.

**Comment by martinussuherman** [comment]
PR merged, closing this.

**Comment by perarnborg** [comment]
Now published in v3.10.2
