### ISSUE TITLE
how to logout silently?

### ISSUE THREAD

**Issue by LazeBear** [perarnborg/vuex-oidc#17]
Consider there are two separate sites, both authenticated with the same single sign-on system. Let's call them, site A and site B. 

If I log out from site B, I do get that `OIDC user is signed out` message logged to the console. However, I'm still acted as a signed in user, and can still access those protected routes. 

What I want to achieve is, I want to log out the user on site A silently when receiving that logout message. (Basically, reset the state in the store, but I couldn't find the action to do that)

Is there any other solution rather than force a page refresh?

**Comment by LazeBear** [comment]
I used `store.commit('oidcStore/unsetOidcAuth');` and it does log me out silently

**Comment by perarnborg** [comment]
Good job figuring this out.

I should probably add this behaviour to vuex-oidc itself so implementation won’t need to do this. I will do this in the next release and ping you here (and re-close issue) when that version is in place.

**Comment by perarnborg** [comment]
As of v1.11.0 vuex-oidc will do `store.commit('oidcStore/unsetOidcAuth')` when a token is expired (that is to say sign out the user in vuex).
