### ISSUE TITLE
Get the latest access_ Token passed  "offline_access"

### ISSUE THREAD

**Issue by baboon-king** [perarnborg/vuex-oidc#180]
I didn't find any way in the  ["Actions"](https://github.com/perarnborg/vuex-oidc/wiki#api)

What should I do?

thinks

**Comment by perarnborg** [comment]
Sorry for not replying sooner! Are you still invested in this @baboon-king ?

Could you please provide more information about what you are trying to do?

**Comment by baboon-king** [comment]
@perarnborg 

haha! long time no see! welcome back.
I don't remember what I wanted to do.
maybe... 

> How to use "refresh_token" to obtain the latest "access_token"

It's been too long. I don't need to solve this problem. Thank you for your attention.

Thank you reply

Baboon King
