### ISSUE TITLE
Silent refresh does not renew idp session

### ISSUE THREAD

**Issue by cmyildirim** [perarnborg/vuex-oidc#19]

**Comment by cmyildirim** [comment]
So after session finishes on identity server side silent refresh does not work anymore.
Let's say we have access token lifetime of 30 minutes, and idp session is 2 hours (defined by cookie). Silent refresh works 3 times refreshing the token but after 2 hours is finished it return error message login_required

**Comment by perarnborg** [comment]
I might be out of my depth here, but I do not know how the client would control if the session at the idp is refreshed or not? What will happen when silent refresh is made is basically that an iframe will navigate to the url provided in silent_redirect_uri. What happens at the OP is beyond the clients control as far as I can see.

**Comment by perarnborg** [comment]
@cmyildirim Did you see my reply? As far as I can till this issue is not something that should be fixed by this library. I will close the issue if I do not hear back from you.
