### ISSUE TITLE
migrating from oidc-client to oidc-client-ts

### ISSUE THREAD

**Issue by apavelm** [perarnborg/vuex-oidc#194]
Since "oidc-client" is abandoned and not maintained anymore. Also, many analyzers complain of this library and it's dependencies.
I suggest following the recommendation of "oidc-client" library and migrate to "oidc-client-ts" it should be fully compatible.

**Comment by manpreet-compro** [comment]
@apavelm There is discussion around this on the thread - #177

**Comment by perarnborg** [comment]
v4 now uses oidc-client-ts
