### ISSUE TITLE
Should isAuthenticated be checking id_token or access token?

### ISSUE THREAD

**Issue by joshrobertson92** [perarnborg/vuex-oidc#20]
I'm trying to establish why my app does a full page post to the identity server then back to the call back uri when the `id_token` has expired.

From what i can see the below code checks the id_token expiry, is this correct or should it check the access token? 

`const isAuthenticated = (state) => {
    if (state.id_token && !tokenIsExpired(state.id_token)) {
      return true
    }
    return false
  }`

Also when the `oidcCheckAccess` method is fired it only seems to call `authenticateOidcSilent` if the route is public?

`getUserPromise.then(user => {
          if (!user) {
            if (isAuthenticatedInStore) {
              context.commit('unsetOidcAuth')
            }
            if (route.meta.isPublic) {
              if (oidcConfig.silent_redirect_uri) {
                context.dispatch('authenticateOidcSilent')
              }
            } else {
              context.dispatch('authenticateOidc', route.path)
              hasAccess = false
            }
          }
          resolve(hasAccess)`

**Comment by joshrobertson92** [comment]
Thanks for your response.

That works much better, any chance of this being released onto npm?

**Comment by perarnborg** [comment]
@joshrobertson92 Yes, was published just now.
