### ISSUE TITLE
Leftover import from oidc-client

### ISSUE THREAD

**Issue by mediafreakch** [perarnborg/vuex-oidc#201]
Just noticed that in v4.0 there's a left-over from `oidc-client` in the [type declarations](https://github.com/perarnborg/vuex-oidc/blob/57741307a98aa3bd649f014dfdb6af7fb5b54025/index.d.ts#L2). 

I'm putting this here for anyone that has time to work on it.

**Comment by perarnborg** [comment]
@mediafreakch Thanks for catching! Fixed in v4.0.1.
