### ISSUE TITLE
End session

### ISSUE THREAD

**Issue by Samtronic** [perarnborg/vuex-oidc#21]
Hi !

When I disconnect the session I have always this message in my frontEnd

oidc-client.min.js?dd17:3 Uncaught (in promise) Error: End-User authentication is required
    at new ErrorResponse (oidc-client.min.js?dd17:3)
    at ResponseValidator._processSigninParams (oidc-client.min.js?dd17:49)
    at ResponseValidator.validateSigninResponse (oidc-client.min.js?dd17:49)
    at eval (oidc-client.min.js?dd17:3)

export const oidcSettings= {
  authority: `${process.env.VUE_APP_OIDC_SERVER}/oauth2/auth`,
  client_id: 'dassda',
  redirect_uri: `${window.location.origin}/oidc-callback/`,
  response_type: 'id_token token',
  scope: 'openid profile email roles',
  automaticSilentRenew: true,
  silent_redirect_uri: `${window.location.origin}/silent-renew-oidc.html`,
  post_logout_redirect_uri: `${window.location.origin}/`,
  loadUserInfo: false,
  metadata: {
    issuer: `${process.env.VUE_APP_OIDC_SERVER}/oauth2`,
    jwks_uri: `${process.env.VUE_APP_OIDC_SERVER}/oauth2/certs`,
    end_session_endpoint: `${process.env.VUE_APP_OIDC_SERVER}/oauth2/session/end`,
    authorization_endpoint: `${process.env.VUE_APP_OIDC_SERVER}/oauth2/auth`
  }
}

Thanks
Steven

**Comment by perarnborg** [comment]
Thanks for the input!

This should be fixed in v1.12.1. Let me know if you are still seeing this.

**Comment by Samtronic** [comment]
Everything seems to work well

Thank you for your work
Steven
