### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Samtronic** [perarnborg/vuex-oidc#22]
Hi !
In your documentation you wrote
computed: {
    ...mapGetters([
      'oidcIsAuthenticated',
      'oidcUser',
      'oidcAccessToken',
      'oidcAccessTokenExp',
      'oidcIdToken',
      'oidcIdTokenExp',
      'oidcAuthenticationIsChecked'
    ]),

It should be

computed: {
    ...mapGetters('oidcStore', [
      'oidcIsAuthenticated',
      'oidcUser',
      'oidcAccessToken',
      'oidcAccessTokenExp',
      'oidcIdToken',
      'oidcIdTokenExp',
      'oidcAuthenticationIsChecked'
    ]),

**Comment by perarnborg** [comment]
This actually depends on if you have created your vuex module as a namespaced module or not.

```
oidcStore: vuexOidcCreateStoreModule(oidcSettings, { namespaced: true })
```

**Comment by Samtronic** [comment]
Yes thank you, I forgot the namespace

Thanks
