### ISSUE TITLE
Update oidc-client lib

### ISSUE THREAD

**Issue by NunoSav** [perarnborg/vuex-oidc#23]
Authorization code flow was implemented with version 1.6 and this lib is using 1.5.4.

Any plan on updating it? Thanks

**Comment by perarnborg** [comment]
@NunoSav I will update the dependency within short unless I run into anything unexpected when doing so. However I will probably not have the time to test code flow with vuex-oidc myself any time soon.

**Comment by perarnborg** [comment]
vuex-oidc with updated oidc-client is published as v1.13.0
