### ISSUE TITLE
a lot of oidc keys in localstorage

### ISSUE THREAD

**Issue by kennyStarfisk** [perarnborg/vuex-oidc#27]
Is it normal that I get a lot of local storage keys of oidc? 
![Screenshot 2019-03-20 at 07 58 18](https://user-images.githubusercontent.com/44225848/54664956-f337d700-4ae5-11e9-8c55-7b7ea116d410.png)

**Comment by Stormsys** [comment]
i think this is related to #29 this happens because every page load causes a redirect cycle to openid connect server

**Comment by perarnborg** [comment]
That sounds right. oidc-client stores data in localstorage, and there will be a new entry there after each authentication. The current behaviour that each page reload triggers reauthentication will cause more of these entries.

**Comment by perarnborg** [comment]
Version 1.15.0 now loads user from storage so you will probably see less keys in the storage. However, the library will still be a creating history of old (expired) tokens from earlier authentications in the storage since this is the way oidc-client works. Just not as many as before.
