### ISSUE TITLE
Silent-renew immediately after login? 

### ISSUE THREAD

**Issue by kennyStarfisk** [perarnborg/vuex-oidc#28]
Is this silent-renew action normal immediately after I login? 
![Screenshot 2019-03-20 at 10 41 05](https://user-images.githubusercontent.com/44225848/54677170-a31b3d80-4b02-11e9-9274-4bdf8d3724b8.png)

**Comment by perarnborg** [comment]
It is not expected. The Access token did expire event is triggered (which is originally dispatched from oidc-client), and if this happens directly after signin I would suspect that oidc-client thinks that there is something wrong with the tokens it gets from the redirect callback.

**Comment by ayZagen** [comment]
You should check your identity providers access_token lifetime. If it is short, this is expected.

**Comment by ayZagen** [comment]
you can copy the access_Token and you can check its lifetime with a jwt parser (if it is not opaque but jwt, which probably it is ) or using [jwt.io](https://jwt.io/) the `exp` field in payload.
