### ISSUE TITLE
Not redirecting to authority

### ISSUE THREAD

**Issue by alexlvovich** [perarnborg/vuex-oidc#3]
setup according to readme file but no link is redirect redirected to authority's page. please help
[web.zip](https://github.com/perarnborg/vuex-oidc/files/2106815/web.zip)

**Comment by perarnborg** [comment]
@alexlvovich Your issue should be fixed in v1.5.7. Please reopen issue if that is not the case.

**Comment by alexlvovich** [comment]
@perarnborg, it works thanks a lot for a quick fix.
