### ISSUE TITLE
oidcIsAuthenticated not working after login

### ISSUE THREAD

**Issue by FradaL** [perarnborg/vuex-oidc#33]
Hi, I am working with vuex-oidc, but I have a problem, after the login I'm try capture the value -oidcIsAuthenticated, I think that should be True, but is False, can you help me?  can be a error of  version 1.15.1?

![image](https://user-images.githubusercontent.com/11936209/55255592-a27c5880-5220-11e9-9bad-d99947f235f4.png)

**Comment by perarnborg** [comment]
I could not recreate this at my first attempt. Does it work if you use an order version (like v1.14.0)?

**Comment by FradaL** [comment]
Hi Perarnborg, thanks for you help!

I did weekend tryed, Actually is "Working" but i have a other error, after login, the callback redirect to signin-oidc-error and the console show this: 

![image](https://user-images.githubusercontent.com/11936209/55419601-5b4cdb00-5532-11e9-9806-58858ff59c2c.png)

Sorry, you can help me to find  error?

**Comment by perarnborg** [comment]
@FradaL The error with no matching state found in storage is typically thrown when the url/fraction parameters in the callback do not match what is expected given the state that was saved before the authentication.

The most common reason for this is that something is off with the route definitions or redirectUri setting. I would advice you to go through the authentication with a browser inspector (like Chrome Web Inspector) open at the network tab with the preserve logs option checked. Make sure that the redirection loop matches your settings. And also make sure that no additional redirection is made.

Oh, and one more thing: are you using server side rendering in your app?

**Comment by FradaL** [comment]
@perarnborg  Thanks for you help! I solutioned all problems!

**Comment by perarnborg** [comment]
@FradaL OK, that's great news!
