### ISSUE TITLE
route.meta is an array

### ISSUE THREAD

**Issue by ysaakpr** [perarnborg/vuex-oidc#34]
https://github.com/perarnborg/vuex-oidc/blob/890a88198d767714d3c9a9bf663c89cc9c629c55/src/store/create-store-module.js#L83

route.meta is an array and i am not able to use it in my vue version,

**Comment by ysaakpr** [comment]
oh..i was using nuxt js router, and in which the route meta is an array

**Comment by perarnborg** [comment]
Currently, vuex-oidc is built to work with vue-router. I might look into supporting nuxt though.

**Comment by israelfloresdga** [comment]
@ysaakpr How did you implemented vuex-oidc in Nuxt? I saw your fork, but I don't have a clue how to do the nuxt config.

**Comment by perarnborg** [comment]
I have not had the time to do a proper implementation in nuxt. One thing that comes to mind is that the callback Component should probably use the mounted() hook in stressad of created() like the example does. Probably the library need adjustments as will, both for the meta array and probably to not check access on the server side.

But these are only thoughts, hopefully I can take some time for this in the near future.

**Comment by ysaakpr** [comment]
@israelfloresdga , I had some changes and made it work with vuex-oidc, but I haven't vuex-oidc as is, rather I modified a couple of lines of code. It's not in a sharable situation. I will put some time and will see if I can patch back the master. 

And I haven't tested it for server-side rendering as well, because my usage is SPA

**Comment by perarnborg** [comment]
There is now information in the wiki on how to use vuex-oidc with Nuxt in SPA mode. Also an example of an implementation in https://github.com/perarnborg/vuex-oidc-example-nuxt/
