### ISSUE TITLE
Cannot store token in session storage

### ISSUE THREAD

**Issue by leopoldmandic** [perarnborg/vuex-oidc#35]
I used your example as my starting point but I can't store token in session storage. I read your source code and in **oidc-helpers.js** there is:
```
const defaultOidcConfig = {
  userStore: new WebStorageStateStore(),
  loadUserInfo: true
}
```
which is used for building oidc UserManager object.
`new WebStorageStateStore()` is by default storing in localStorage (https://github.com/IdentityModel/oidc-client-js/blob/dev/src/WebStorageStateStore.js) and I can't pass any parameters to it. Can you help me with this?

**Comment by perarnborg** [comment]
You should be able to import WebStorageStateStore from oidc-client and instantiate your own new WebStorageStateStore() that you pass in as userStore in the config. It will override the default. I can write you an example after the weekend.

**Comment by leopoldmandic** [comment]
Sorry for delayed response. I did try putting my WebStorageStateStore() but it didn't work out. I would be grateful if you could write an example for session storage (and maybe put it in your default example for anyone else trying same thing). Thank you in advance.

**Comment by perarnborg** [comment]
OK, so this is how you would change the example app to use sessionStorage:

```
import Vue from 'vue'
import Vuex from 'vuex'
import { vuexOidcCreateStoreModule } from 'vuex-oidc'
import { oidcSettings } from './config/oidc'
import { WebStorageStateStore } from 'oidc-client'

Vue.use(Vuex)

export default new Vuex.Store({
  modules: {
    oidcStore: vuexOidcCreateStoreModule(
      {
        ...oidcSettings,
        userStore: new WebStorageStateStore({ store: window.sessionStorage })
      },
      // Optional OIDC store settings
      {
        namespaced: true,
        dispatchEventsOnWindow: true
      },
      // Optional OIDC event listeners
      {
        userLoaded: (user) => console.log('OIDC user is loaded:', user),
        userUnloaded: () => console.log('OIDC user is unloaded'),
        accessTokenExpiring: () => console.log('Access token will expire'),
        accessTokenExpired: () => console.log('Access token did expire'),
        silentRenewError: () => console.log('OIDC user is unloaded'),
        userSignedOut: () => console.log('OIDC user is signed out')
      }
    )
  }
})
```

**Comment by leopoldmandic** [comment]
Thanks a lot mate. You did great job with this wrapper.

**Comment by ux-engineer** [comment]
`'userStore' does not exist in type 'VuexOidcClientSettings'.ts(2345)`
