### ISSUE TITLE
Minor correction to wiki

### ISSUE THREAD

**Issue by coolhome** [perarnborg/vuex-oidc#36]
Under the header `Optional: setup silent renew callback` (https://github.com/perarnborg/vuex-oidc/wiki#9-optional-setup-silent-renew-callback) the parameter `silentRedirectUri` should be `silent_redirect_uri`.

**Comment by perarnborg** [comment]
Thanks for pointing out this inconsistency!

As of changes made for #25 both camelCase and snake_case are valid for this setting (and other settings that oidc-client have that are snake_cased. I have changed the docs now to consistently use snakeCase both in examples and in text.

**Comment by coolhome** [comment]
@perarnborg Nice!

Just a side note I think you can enable a setting for the repository to allow pull requests into the wiki
https://help.github.com/en/articles/changing-access-permissions-for-wikis
