### ISSUE TITLE
SilentRenew not working after refreshing the page using webpack

### ISSUE THREAD

**Issue by Timoms** [perarnborg/vuex-oidc#43]
Im not quite sure how to reproduce... 
But im implementing vuex-oidc and its working fine with silent-renew until I change something in the component (to force a wepack based reload). 

After that, it seems the event to silent renew is not fired anymore. 
In the console I can see "Token is about to expire" and after that "Token is expired" - so OIDC is still working. 

Even a force reload isn't fixing the problem. 
But when clearing the application-data its working fine again. 

Is it just me or is there a bug behind this problem.. or, just general incompatibility with webpack?

Thanks in advance!

_Using Latest Chrome-Based Software_

**Comment by perarnborg** [comment]
Ok, this is not something I have run into myself using webpack. But I can imagine that this could be an issue when using webpacks dev server with hot reload. 

Should be fixable, but I am on vacation at the moment and will not be able to lok into this until mid July.

**Comment by Doormouse2House** [comment]
I suspect the OP issue was caused by the same thing in that the webpack reload is seeing OidcIsAuthenticated as false because the access_token is expired.  Anyway, happy to create a new issue.

I'll answer your request for clarity in the new ticket...

**Comment by perarnborg** [comment]
@Timoms I spent some time to try to recreate this issue (webpack dev server hot reload causing automatic silent renew to stop working), but to no success. Is it any component update that causes this, or is it something more specific that breaks the implementation?

Do you have the time to create an example project where the issue can be seen?

**Comment by Timoms** [comment]
@perarnborg Hey. thanks for your time. 
I am currently converting all my projects to NuxtJS - If the problem shows up even in my NuxtJS projects, ill let you know.

**Comment by cmfc31** [comment]
@Timoms Oh, that's happening to me right now. Every time I manually refresh the page, close the app and open it on a new tab, silent-renew stops working.  Even if I logout and login again, I need to clear the application data from my browser to make it work again.

**Comment by cmfc31** [comment]
@perarnborg I found the issue. The problem appears when I use vuex-persistedstate plugin
https://github.com/robinvdvleuten/vuex-persistedstate

I started using this plugin because when I refresh my page I lose my vuex state. So, somehow when I use it along with vuex-oidc silent-renew stops working on refresh. Could you make it work with persistedstate plugin?

**Comment by cmfc31** [comment]
@perarnborg I think I found a workaround storing my own vuex state on a separate module. So, I'll only use persistedstate in my module. Leaving vuex-oidc on it's own. Here's how my store.js looks right now.

```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import { vuexOidcCreateStoreModule } from 'vuex-oidc'
import { oidcSettings } from './config/oidc'
import createPersistedState from 'vuex-persistedstate'
import SecureLS from 'secure-ls'
const ls = new SecureLS({ isCompression: false })

Vue.use(Vuex)

const moduleA = {
   state: {
      a: 'a'
   },
   mutations: {
      updateA(state) {
         state.a += 'a'
      }
   }
}

export default new Vuex.Store({
   modules: {
      moduleA: moduleA,
      oidcStore: vuexOidcCreateStoreModule(
         oidcSettings,
         // Optional OIDC store settings
         {
            dispatchEventsOnWindow: true
         },
         // Optional OIDC event listeners
         {
            userLoaded: user => console.log('OIDC user is loaded:', user),
            userUnloaded: () => console.log('OIDC user is unloaded'),
            accessTokenExpiring: () => console.log('Access token will expire'),
            accessTokenExpired: () => console.log('Access token did expire'),
            silentRenewError: () => console.log('OIDC user is unloaded'),
            userSignedOut: () => console.log('OIDC user is signed out'),
            oidcError: payload => console.log('OIDC error', payload)
         }
      )
   },
   plugins: [
      createPersistedState({
         key: 'vuex_a',
         paths: ['moduleA'],
         storage: {
            getItem: key => ls.get(key),
            setItem: (key, value) => ls.set(key, value),
            removeItem: key => ls.remove(key)
         }
      })
   ]
})

```

Well, right now it seems like everything is working fine! Silent-renew still works on page reloads. And I still have my persistedstate 😄.
