### ISSUE TITLE
OAuth2 Possible?

### ISSUE THREAD

**Issue by christophstockinger** [perarnborg/vuex-oidc#44]
Hi @perarnborg, 
is it possible to use your Packager for a simple OAuth2 implementation as well?

**Comment by perarnborg** [comment]
@christophstockinger Not 100% sure what you mean, but the ([implementation example](https://github.com/perarnborg/vuex-oidc-example)) is an implementation of authentication against a google OAuth 2.0 client ID. So I think the answer is yes.

**Comment by christophstockinger** [comment]
Okay. I was just looking at the documentary then. 

But it is not possible to work with a password grant.
So that I request an OAuth2 server with the username and password in my frontend app and then get the tokens if these permissions are correct.

**Comment by perarnborg** [comment]
@christophstockinger I understand. I believe there is a feature request for this in oidc-client that is under discussion. If it gets done in oicd-client, it will be supported in this package soon after that, but not before that is done as things look right now.

**Comment by perarnborg** [comment]
[This is the issue in oidc-client](https://github.com/IdentityModel/oidc-client-js/issues/234)

**Comment by christophstockinger** [comment]
thx
