### ISSUE TITLE
How to delay configuration of oidcSettings?

### ISSUE THREAD

**Issue by bey6** [perarnborg/vuex-oidc#46]
I want to use a `config.json` file to save the server urls, so i need to request it with axios. but the configuartion of the oidcSettings is using before i request.

could you help me?

thanks.

**Comment by perarnborg** [comment]
I understand! The package does not have direct support for this, but I believe you could use the vuex function registerModule to create the oidc vuex module dynamically after the axios request is done.

An example where a vuex module is created dynamically: https://alligator.io/vuejs/vuex-dynamic-modules/

**Comment by bey6** [comment]
I will try it, thank you very much.
