### ISSUE TITLE
Vue Error: No state in response

### ISSUE THREAD

**Issue by zrkcode** [perarnborg/vuex-oidc#49]
npm：
"oidc-client": "^1.9.0",
"vuex-oidc": "^3.0.0"

Error: No state in response
    at e.t [as readSigninResponseState] (oidc-client.min.js?ac2e:1)
    at e.t [as processSigninResponse] (oidc-client.min.js?ac2e:1)
    at e.t [as _signinEnd] (oidc-client.min.js?ac2e:47)
    at e.t [as signinRedirectCallback] (oidc-client.min.js?ac2e:47)
    at eval (index.js?dcda:307)
    at new Promise (<anonymous>)
    at Store.oidcSignInCallback (index.js?dcda:306)
    at Array.wrappedActionHandler (vuex.esm.js?591a:732)
    at Store.dispatch (vuex.esm.js?591a:437)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?591a:331)

By Debug, I find url is " /oidc-callback",so nothing in respone
![image](https://user-images.githubusercontent.com/20158277/63904568-175bf480-ca44-11e9-83f7-5500c5e34690.png)

so I add the params for oidcSignInCallback:
![image](https://user-images.githubusercontent.com/20158277/63904624-44a8a280-ca44-11e9-9e4b-fdd6246df9ad.png)

Make it work:
![image](https://user-images.githubusercontent.com/20158277/63904702-86d1e400-ca44-11e9-80de-cace17fbbea8.png)

End：
Is there any other solution?

**Comment by perarnborg** [comment]
@zrkcode I do not quite get why `this._redirectNavigator.url` does not get the open id response parameters, since it should be set to window.location.href (this happens inside this package's dependency [oidc-client](https://github.com/IdentityModel/oidc-client-js).

Anyway, I guess we could add a parameter to the oidcSignInCallback action like you suggest, since òidc-client has that parameter on it's ÙserManager.signinRedirectCallback`. I will add that to `vuex-oidc` within short.

**Comment by zrkcode** [comment]
> @zrkcode I do not quite get why `this._redirectNavigator.url` does not get the open id response parameters, since it should be set to window.location.href. This happens inside this package's dependency [oidc-client](https://github.com/IdentityModel/oidc-client-js).
> 
> Anyway, I guess we could add a parameter to the oidcSignInCallback action like you suggest, since òidc-client has that parameter on it's `ÙserManager.signinRedirectCallback`. I will add that to vuex-oidc within short.

All right

**Comment by perarnborg** [comment]
@zrkcode If you update to v3.1.1 your have an optional url parameter on the oidcSignInCallback action.

**Comment by zrkcode** [comment]
@perarnborg Thanks
