### ISSUE TITLE
How to get access token 

### ISSUE THREAD

**Issue by thoraj** [perarnborg/vuex-oidc#5]
Thanks for sharing how to combine vuex and oidc-client. This is really helpful. 

When making calls to protected apis, how do I get the access_token from the store?

Are there some getters missing in the store, or are we supposed to "extend" the store ourselves to access more of the state?

**Comment by perarnborg** [comment]
@thoraj Thanks for your input! Currently there is a getter for the user, but not for access_token (or id_token). For consistency, I will add getter oidcAccessToken and oidcIdToken. I will deliver a patch with these, hopefully this weekend.

In the meantime, you can access the access_token with

store.state.oidcStore.access_token

Or, with mapState if you are in a component.

**Comment by thoraj** [comment]
Thanks for your quick reply. 

Digging into the state as you suggested works OK. I will change to using the getter once it is place. 

Thanks.

**Comment by perarnborg** [comment]
Getters for access_token and id_token are added in v1.5.8. See API section of the wiki.
