### ISSUE TITLE
Event.detail is empty object in vuexoidc:userLoaded?

### ISSUE THREAD

**Issue by GordonBlahut** [perarnborg/vuex-oidc#51]
I'm using `dispatchEventsOnWindow: true` and trying to handle `vuexoidc:userLoaded` in a component. The event handler fires, but `event.detail` appears to be an empty object. Unlike the `userLoaded` event within the store itself, the custom window event does not seem to contain the user data. 

It looks like it's intended to be passed as the detail: https://github.com/perarnborg/vuex-oidc/blob/c794f21f69d54382abc9ac65ea458c8b0f04bd1f/src/store/create-store-module.js#L150

Maybe it's conflicting with this? https://github.com/perarnborg/vuex-oidc/blob/c794f21f69d54382abc9ac65ea458c8b0f04bd1f/src/store/create-store-module.js#L30-L35

**Comment by perarnborg** [comment]
Thank you for pointing this out @GordonBlahut! 

The user is indeed intended to be there, and this should be fixed as of v3.1.2.

**Comment by perarnborg** [comment]
(If you are bumping up from < v3 you need to install peer dependency oidc-client manually)

**Comment by GordonBlahut** [comment]
@perarnborg Thanks for the quick fix, I will try it out and let you know.

BTW for your previous change for hash routing, did you look at using $route.fullPath instead of $route.path and manually appending the document.location.search and document.location.fragment? You could possibly entirely avoid any special handling for hash mode since $route.fullPath automatically does not contain the leading # and already includes any query and fragment from the route. It should give consistent results for either mode.

**Comment by perarnborg** [comment]
@GordonBlahut Very good point! I will look into this and probably change it. Thank you for helping out!

**Comment by perarnborg** [comment]
@GordonBlahut Thanks for the tip! The special handling of router hash mode is now removed!
