### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by gregorybleiker** [perarnborg/vuex-oidc#52]
Hi there
I'm struggling getting error handling to work. For instance, if the oidc provider is offline, I would like to show an error message. Is there any events/hooks I can use?

**Comment by perarnborg** [comment]
@gregorybleiker There is currently a getter called `oidcError` that will return any error that has occured in the oidc connection, https://github.com/perarnborg/vuex-oidc/wiki#api.

But I can see the point in introducing an event to be able to listen to when an error occurs. I will look into that for a coming update.

**Comment by perarnborg** [comment]
@gregorybleiker As of v3.1.5 there is an event called oidcError that you can listen to. See [wvent docs](https://github.com/perarnborg/vuex-oidc/wiki#10-optional-setup-oidc-client-event-listeners) or [example repository](https://github.com/perarnborg/vuex-oidc-example)
