### ISSUE TITLE
[Feature Request] Logout without IdP logout.

### ISSUE THREAD

**Issue by cperrin88** [perarnborg/vuex-oidc#53]
I use fusionauth as IdP and they don't expose an end session endpoint in their metadata. I have allready raised ticket with them but I don't know when this will be fixed.

Since the logout seems to be an optional endpoint anyway, maybe it is possible to at least create a client side logout.

**Comment by perarnborg** [comment]
Sounds like a good idea to add an action to clear the user in the browser. I will look in to this within short.

**Comment by perarnborg** [comment]
@cperrin88 as of v3.1.4 there is an action (`removeUser`) that signs out the user in vuex and browser storage.

**Comment by cperrin88** [comment]
You are awesome! Thanks a lot!
