### ISSUE TITLE
How can I check authenticated status at startup?

### ISSUE THREAD

**Issue by GordonBlahut** [perarnborg/vuex-oidc#55]
I'm trying to check if the user is authenticated in my root component's `created` method, but it seems the getters aren't set yet at that point.  
  
Basically, if the user is authenticated I want to run some startup code and wait for it to complete before any child components/routes are processed as many will depend on the initial state being available. 
  
Right now I'm running my auth-dependent code in the `userLoaded` event but it's too late in some cases and no ability to await...

Is there a recommended approach for handling auth checking at startup?

**Comment by perarnborg** [comment]
Currently the authentication will be set the first time in the router middleware, so the created() hook in your root component can not be trusted to run before authentication is set. 

I can look into if this can change, however if you have your oidc callback handled in a vue route (like the example implementation), the root components created() hook after a sign in at the provider would be called before the user is authenticated, and will not be run again after authentication. Depends on what type of stuff you want to do at startup.

**Comment by perarnborg** [comment]
@GordonBlahut As of v3.1.6 the getOidcUser action returns a promise that you can await, so you could use this to check authentiaction at start up.

```
async created () {
  const user = await this.getOidcUser()
  if (user) {
    // Authenticated
  } else {
    // Not authenticated
  }
},
methods: {
  ...mapActions('oidcStore', ['getOidcUser'])
}
```

However, as I pointed out in the comment above, remember that the created() hook in your app's root component will not be run again if you authenticate (with the open id callback) the user within the vue app like the example app does. So you need to figure out a way to handle that, for example to run some code in the callback route or possibly to have the callback page be outside of your vue app, like the silent renew callback is in the example.

**Comment by perarnborg** [comment]
@GordonBlahut Did you look at my suggestion above?

**Comment by GordonBlahut** [comment]
I think I can do what I need to do within a beforeEnter on my top level route. 

Being able to await the `getOidcUser` call is indeed helpful so thank you very much for that change.

**Comment by perarnborg** [comment]
Ok, good luck!

That’s right, Vue will not wait for async operations in create hooks before the lyfe cycle continues.

**Comment by rac0316** [comment]
Found an issue with this method - if you're not currently signed in or if you're coming back to an oidc-callback method, getOidcUser will throw an error because it's trying to set user.profile into the store. I believe if you just let this gracefully fail instead of error-ing out, then the error will go away and still allow us to use getOidcUser to get user information at application start. This would also allow us to keep the oidc-callback in the main Vue App instead of having to split it out.

Currently I can work around this by surrounding getOidcUser in a try/catch in the main App.vue file.

![image](https://user-images.githubusercontent.com/49078032/73784467-819b6280-4763-11ea-87b2-72751ccfa9c8.png)

**Comment by perarnborg** [comment]
@rac0316 Thanks for pointing this out, I will look into this within short.

**Comment by anbraten** [comment]
I would like to check `oidcIsAuthenticated` in a component route guard. But it seems the store / auth state isn't loaded at that point. Awaiting with `await store.dispatch('oidc/getOidcUser');` doesn't seem to help here. Would be nice to use something similar to `oidcCheckAccess` that only loads the store from `oidc-client` without redirecting? 🤔 

``` js
export default {
  name: 'Home',

  async beforeRouteEnter(to, from, next) {
    // TODO: wait for store to be loaded

    const isAuthenticated = store.getters['oidc/oidcIsAuthenticated'];

    console.log(isAuthenticated);

    if (!isAuthenticated) {
      next({ name: 'auth-login' });
      return;
    }

    next();
  },

  setup(props, context) {
    const { $store, $router } = context.root;

    // ....
  
    return {
    };
  },
};
```
