### ISSUE TITLE
[Feature Request] Login with popup

### ISSUE THREAD

**Issue by cperrin88** [perarnborg/vuex-oidc#56]
Can you maybe add a way to log in with a popup instead of the full page redirect? I think there is this `signinPopup` method for that.

**Comment by perarnborg** [comment]
Good point! Will look into this!

**Comment by perarnborg** [comment]
@cperrin88 as of v3.3.0 there is a `authenticateOidcPopup` action that implements `signinPopup`

**Comment by perarnborg** [comment]
(You also need to provide a callback for the popup authentication: https://github.com/perarnborg/vuex-oidc-example/blob/caaaef0e4508200dfd8fa4fb7e1762c2269822c1/src/router.js#L39)

**Comment by GordonBlahut** [comment]
@perarnborg FYI it looks like you duplicated a setting here related to this change:
https://github.com/perarnborg/vuex-oidc/blob/fc97ccbb979a6debb27ede4988865a3d9f830fe6/src/services/oidc-helpers.js#L17-L29

`popupRedirectUri` is on both lines 26 & 28. Not sure if just an unintended duplication, or if if the second value was meant to be a different setting and mistyped.

**Comment by perarnborg** [comment]
@GordonBlahut Thanks for pointing this out! This was an unintended duplication. I'll remove the second one!

Cheers!
