### ISSUE TITLE
[Feature Request] Non-redirecting logout

### ISSUE THREAD

**Issue by nixxholas** [perarnborg/vuex-oidc#57]
https://github.com/IdentityModel/oidc-client-js/issues/258

Not sure if we can bring this over! :)

**Comment by perarnborg** [comment]
Sounds like a good plan! Feel free to look into implementing the feature if you are willing and able! :) 

Otherwise I will look at this in a few weeks, I won't have the bandwidth before that.

**Comment by perarnborg** [comment]
As of v3.8.0 there is a signOutOidcSilent action that implements this. The signout is performed in a hidden iframe.

**Comment by perarnborg** [comment]
Update: Use at least v3.9.6 if you want to use signOutOidcSilent.
