### ISSUE TITLE
No key matching kid or alg found in signing keys

### ISSUE THREAD

**Issue by mortensassi** [perarnborg/vuex-oidc#58]
Followed your step by step tutorial but unfortunately I'm having an issue with the signingKeys:

`Error: "No key matching kid or alg found in signing keys"`

this is my config:

```js
export const oidcSettings = {
    authority: authority,
    clientId: 'myClientID', 
    redirectUri: redirectUri,
    responseType: 'id_token',
    scope: 'openid email',
    loadUserInfo: true,
    metadata: {
        issuer: `https://login.microsoftonline.com/${tenant}/v2.0`,
        authorization_endpoint: `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/authorize`,
        jwks_uri: `https://login.microsoftonline.com/${tenant}/discovery/v2.0/keys`,
        end_session_endpoint: `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/logout`,
    },
}
```

Got any clues what i am doing wrong?

**Comment by razvanreb** [comment]
I think you should look at the oidc-client library instead. Your issue seems not to be related to Vuex-oidc . 
e.g. https://github.com/IdentityModel/oidc-client-js/issues/264

**Comment by perarnborg** [comment]
@mortensassi I agree with @razvanreb. There are a few other closed issues that look similar in oidc-client as well. My first suggestion would be to look through those:

https://github.com/IdentityModel/oidc-client-js/issues?q=is%3Aissue+No+key+matching+kid+or+alg+found+in+signing+keys+is%3Aclosed

**Comment by mortensassi** [comment]
I found out we just got the wrong keys-url and now it is working! Sorry for wasting your time and thank you!

**Comment by titilambert** [comment]
@mortensassi What is the correct `jwks_uri` ? I have the same issue ...

**Comment by mortensassi** [comment]
> @mortensassi What is the correct `jwks_uri` ? I have the same issue ...
hey @titilambert this is in my conf – write me if you need further help!

```js
metadata: {
// [....]
jwks_uri: `https://login.microsoftonline.com/${tenant}/discovery/v2.0/keys`,
}
```
