### ISSUE TITLE
oidcIsAuthenticated is bound to access_token expiry instead of id_token

### ISSUE THREAD

**Issue by Doormouse2House** [perarnborg/vuex-oidc#59]
To me it seems as though the implementation of oidcIsAuthenticated is correct insofar as when the state of id_token flips, the OIDC client is considered no longer authenticated.

Unfortunately, when I look at the user retrieved as part of the authentication process, I can see that the "expires_at" or user.expired field is using the access_token expiry and not the id_token expiry. In my case, the accessTokenExpiring and accessTokenExpired events trigger (as expected based on the expiry time), however because I was binding oidcIsAuthenticated to my component visbility as soon as the access_token expired I lost visibility of the component. Access tokens should be short-lived, and ID tokens long-lived, and in fact by refreshing my browser the ID token was presented to the AS which dutifully gave me a new access token starting the problem over.

Right now, I'm only coming with insight on the problem, as I don't have a solution. My temp workaround was to rely solely on the middleware, but unfortunately that does mean Vue will display the protected resource for a brief second before the middleware kicks in - something that couldn't work in production.

**Comment by Doormouse2House** [comment]
I'm not an expert, and hopefully one chimes in, however my understanding is that the access_token is supposed to be used for access to a protected resource, most commonly an API, and as mentioned is commonly short-lived.
https://auth0.com/docs/protocols/oidc#access-tokens

The id_token contains the identity data for the user, is longer lived, and also includes claims which can be validated by the AS, allowing the AS to generate a new access_token if that has expired.  You'll note that in the ID token (which is a JWKS file) there's a field "exp" which is different from the access_token expiry:
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by Doormouse2House** [comment]
> Do I understand correctly that the problem is that when the access_token expires you do not want the user to be signed out of the app? But instead you want the id_token to decide if the user has access to the vue app? Sorry if I have misunderstood you!
Yes, the access_token expiry means that the authenticated user can no longer access an API, but doesn't mean that the session is necessarily dead.  Possibly a silent_refresh needs to happen before the access_token expires, but that seems like an opinionated decision of the App Owner.

I really think the [documentation around using oidcIsAuthenticated](https://github.com/perarnborg/vuex-oidc/wiki#5-optional-control-rendering-in-app-layout-or-common-components) needs to change, as this is what caused my problem...

**Comment by Doormouse2House** [comment]
I can update the docs when you're clear on how you want to approach.  I wouldn't let me near your code : )

**Comment by perarnborg** [comment]
OK, my idea has been to bind app access to the life time of the access_token, just like you have figured out. And if you want the session to live longer you would implement automatic silent renew of the access_token (as exampled in the docs). 

But perhaps this is a little opinionated, and I am not against introducing a setting to have access control set up against the id_token, even though I believe that the currrent behaviour of having the same access control on the vue app as any protected api resources would be the default option.

**Comment by perarnborg** [comment]
As of v3.5.0 there is now a setting to make the access_token control oidcIsAuthenticated

`oidcStore: vuexOidcCreateStoreModule(oidcSettings, { namespaced: true, isAuthenticatedBy: 'access_token' })`

**Comment by Doormouse2House** [comment]
Thanks @perarnborg.
