### ISSUE TITLE
Use with Quasar starter pack

### ISSUE THREAD

**Issue by raduen** [perarnborg/vuex-oidc#6]
Hello,

Is thier een way to use this with Quasar starter pack?

I'm having trouble understanding how to...

Gr,
Raduen

**Comment by perarnborg** [comment]
@raduen I do not have any experience of Quasar, so I am not sure of how you would implement vuex-oidc with Quasar.

That being said my guess is that as long as you use Vuex for state management and the Vue router you should be able to use it... What kind of problems are you having?

**Comment by patrickmonteiro** [comment]
> Hello,
> 
> Is thier een way to use this with Quasar starter pack?
> 
> I'm having trouble understanding how to...
> 
> Gr,
> Raduen


To work in Quasar I had to do:

![image](https://user-images.githubusercontent.com/13258255/45696199-6d889e00-bb39-11e8-87f4-275e56ba2a7d.png)

**Comment by perarnborg** [comment]
I am closing this issue since it seams stale. Issue #7 is also touching Quasar implementation and remains open.
