### ISSUE TITLE
No parameter exposed for passing it forward to signinRedirect() call

### ISSUE THREAD

**Issue by razvanreb** [perarnborg/vuex-oidc#60]
Not able to pass any args to this method
signinRedirect(**args?: any**): Promise<any>;

https://github.com/perarnborg/vuex-oidc/blob/master/src/store/create-store-module.js#L158

I think it would make sense to have an (signinRedirectOptions : any) to authenticateOidc function

**Comment by perarnborg** [comment]
@razvanreb  Good point, I will fix this!

**Comment by perarnborg** [comment]
@razvanreb Do you see a need for this when vuex-oidc dispatches authenticateOidc internally (which it does in the oidcCheckAccess action)? Or only if the action is dispatched by your app?

**Comment by razvanreb** [comment]
> @razvanreb Do you see a need for this when vuex-oidc dispatches authenticateOidc internally (which it does in the oidcCheckAccess action)? Or only if the action is dispatched by your app?

Indeed, I'm dispatching this action myself.  Even if I wouldn't do it like that, I would still need to be able to pass those args, somehow, as it's a deal breaker for me. Your commit looks fine, handling both cases. 

Perhaps, it would make sense to have a separate vuexOidcSettings on the createStoreModule, if more things like these would be needed.

Thank you!

**Comment by perarnborg** [comment]
Yes, I am also leaning towards implementing an option for "defatault" signinRedirectOptions. Will add that to the PR and publish the changes within the next days.

**Comment by perarnborg** [comment]
@razvanreb You can now (as of v3.2.0) include options in the payload for the authenticateOidc action. 
```
dispatch('authenticateOidc', {
  redirectPath: '/',
  options: { // This object will be sent as parameter to signinRedirect
    useReplaceToNavigate: true
  }
}
```

You can also specify default options when you create the store module (this is recommended if you want vuex-oidc to always send these arguments while authenticating):

```
vuexOidcCreateStoreModule(
  oidcSettings,
  // Optional OIDC store settings
  {
    namespaced: true,
    defaultSigninRedirectOptions: {
      useReplaceToNavigate: true
    }
  }
)
```

**Comment by SoroTrestal** [comment]
Hello, is there any example code how to use the authenticateOidc dispatch action, I want to authenticate before my app gets loaded.

Right now i'm stuck in a redirect loop, if I use it.

Kind regards
