### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by zredb** [perarnborg/vuex-oidc#64]
Hello, 
      how can I pass "ui_locales" parameter dynamiclly to oidcSettings? It seems no way to set "ui_locales" parameter before the send authetication request, any one has comment?

**Comment by perarnborg** [comment]
Right now the UserManager is created when the vuex module is created. So the only option I can think of is to create the store module asynchronously when you now what parameters you want.

A post on how to create modules dynamically: https://alligator.io/vuejs/vuex-dynamic-modules/

I have not tried this myself though.

**Comment by msodel** [comment]
You can pass payload object in `authenticateOidc `method like this:
```
var payload = { options: { ui_locales: this.$i18n.locale } };
this.authenticateOidc(payload);
```
