### ISSUE TITLE
Log out confusion

### ISSUE THREAD

**Issue by Joshgallagher** [perarnborg/vuex-oidc#65]
Hi,

Great library! Made my life so much easier!

I have looked through the docs and can't tell how to set up 'log out' functionality.

I am using Ory Hydra and they provide both front and back channel log out flows.

Any chance you could point me in the right direction?

**Comment by perarnborg** [comment]
Sorry, the docs could use a overhaul, but I am stretched for time.

To sign out at the provider you should be able to dispatch the action `signOutOidc`.  This triggers the `signoutRedirect` method in [`oidc-client`](https://github.com/IdentityModel/oidc-client-js/wiki).

You can also dispatch action `removeOidcUser` to only sign out from the current app.
