### ISSUE TITLE
removeUser not found

### ISSUE THREAD

**Issue by Timoms** [perarnborg/vuex-oidc#66]
Hey, 

As mentioned in another issue, im currently working with oidc again.
Is it possible, that the documentation for "removeUser" is deprecated? 

![image](https://user-images.githubusercontent.com/26655414/67639937-762fd400-f8f6-11e9-9c79-38cb559976de.png)

Is the method now named differently?

**Comment by perarnborg** [comment]
Sorry if this has caused you trouble. As of v3.3.0 the action is called removeOidcUser just to have the action names more consistently named. However you should still be able to dispatch removeUser as a synonym for removeOidcUser.

**Comment by Timoms** [comment]
Thanks man, it worked fine. 
Had an old version too, thats why there was not a single "removeUser" in the JS 😆!

Cheers! Great work.
