### ISSUE TITLE
vue-router is in needed??

### ISSUE THREAD

**Issue by xyfy** [perarnborg/vuex-oidc#67]
I found the package 'vue-router' was not necessary in source code.  it may used in example,but not in source?   because you just provide a middlewire.

will you reduce this require package in source code & npm package?

**Comment by perarnborg** [comment]
I guess it would make sense to remove the peer dependency for vue-router since it is not mandatory to implement vue-router with this package. I will do that in a future update.

**Comment by xyfy** [comment]
I create a pull request for this issuse

**Comment by perarnborg** [comment]
@xyfy Thanks again for contributing! The change is published in v3.3.1.
