### ISSUE TITLE
oidcSignInCallback don't work Quasar.

### ISSUE THREAD

**Issue by patrickmonteiro** [perarnborg/vuex-oidc#7]
When triggering an oidcSignInCallback action the state error is generated.

![image](https://user-images.githubusercontent.com/13258255/45719096-9e86c400-bb75-11e8-8ab9-a33b0d7d7605.png)

![image](https://user-images.githubusercontent.com/13258255/45719041-7eef9b80-bb75-11e8-946d-c9b4709e4701.png)

**Comment by perarnborg** [comment]
Sorry for a slow response. Can you see what happens in the browser/app before the error occures? Do you get redirected to the authentication server?

On what plattform are you rymning your app, web or device app?

**Comment by perarnborg** [comment]
@patrickmonteiro if you are interested in this still and want to share (some of) your code I can take a look.

**Comment by patrickmonteiro** [comment]
@perarnborg  as I could not implement with quasar, I ended up making an adaptation with the plugin oidc-client.js.
You can look at my github the basic structure I created: [https://github.com/patrickmonteiro/quasarOidcClient](https://github.com/patrickmonteiro/quasarOidcClient)

As I matured my knowledge in OIDC, I can help you adapt your plugin to quasar too soon.

**Comment by perarnborg** [comment]
Sure, any help you want to send my way is welcome!

And thanks for catching the mistake in my docs in #6 , it is corrected adjusted now!

**Comment by consideRatio** [comment]
I also got the exact same error, but I learned that once this happens once, I can refresh the webpage to `example.com/` and it suddenly works fine as the redirect does not end up bouncing around a lot (to Okta and then onwards to Azure AD in my case) while it did this the first time.

Anyhow, since I knew this trick, I realized I could handle the error by redirecting back to `/`, and that worked hehe... It feels quite dirty because I don't grasp whats going on.

**Comment by perarnborg** [comment]
@consideRatio Are you using Quasar as well? One thing I was thinking of - are you using server side rendering?

**Comment by consideRatio** [comment]
@perarnborg I'm not, and the fault was not vuex-oidc I have learned now. It was my OIDC provider who failed to provide me the state if i initiated the request in a certain way.

OT: If you want to use Okta as an Identity Provider (IdP), that in turn redirects to an identity provider like Azure AD, Google, etc, you will need to hardcode the underlying identity provider (Azure AD, Google) with a `idp` query parameter to the first request to Okta. Okta is now aware of this issue.

**Comment by perarnborg** [comment]
@consideRatio ok, thanks for the info!
