### ISSUE TITLE
Guidance on unit / e2e testing approach?

### ISSUE THREAD

**Issue by ckpearson** [perarnborg/vuex-oidc#70]
Hi,

I've integrated vuex-oidc into a vue app I'm building as part of our evaluation of SPA frameworks, and it's working great.

I'm now coming to writing the unit tests and e2e tests (I'm using Jest / Cypress respectively).

The Cypress documentation and best practice indicates that you shouldn't rely on third party systems via redirects, and should instead request tokens programmatically.

So my question/s are:

1. Can I get vuex-oidc to perform the request directly without a browser redirect when I'm running in a Cypress test?
2. If not, is there a way I can bypass vuex-oidc in the tests and provide user data / tokens to vuex-oidc manually at startup?
3. Can I disable silent renew during a test session?

For question 2 I figured it might be possible to provide the state to the vuex store before visiting the applications root url (it's a protected router route), but I'm not sure on how to do this.

Apologies if it's a bit of a newb question / the wrong place to ask, but I'm at a bit of a loss and am **fairly** new to all this.

**Comment by perarnborg** [comment]
I am a bit pressed for time right now so I will not be able to answer your question at length right now. What I can say (to answer your third question) is that you can disable silen renew by removing silentRenewUri from your oidc settings.

**Comment by ckpearson** [comment]
That's fine, I suppose for E2E testing my primary question is whether there's a way I can provide user data ahead of time (perhaps by invoking a store mutation manually) that would mean it believed a user was authenticated?

**Comment by jonasrdm** [comment]
Hello, I have the same questions of @ckpearson. 
I'm very insterested in finding ways to workaround vuex-oidc on e2e tests as well

**Comment by fazulk** [comment]
Have the some question here, Only thing I can think of is writing a substitution module for e2e testing..

**Comment by larzon83** [comment]
I have the same question(s). We're using keycloak and my (not implemented) idea was:

- use CI (of course :))
- start a local keycloak-server
- configure it to mimic your real server
- allow and use implicit flow for the target-client inside the realm
- set token expiration comfortable high
- set this local keycloak-server as authority in vuex-oidc settings while in e2e environment
- in cypress:
- in `before` or `beforeEach` (?), do a `cy.request` to the keycloak rest-api
- because of implicit flow, we're directly getting back the tokens
- set tokens to localStorage as vuex-oidc is expecting it
- when a test then wants to visit a protected route, vuex-oidc sees the token and let you go through

It's not advised to use implicit flow but I think it should be ok while running tests in CI.

What do you think? Probably to naive 😄

**Comment by perarnborg** [comment]
I have not written tests in Cypress, but as I understand it Cypress uses sinon so couldn't stubbing functions in oidc-client be a good option here ([Cypress' stub documentation](https://docs.cypress.io/guides/guides/stubs-spies-and-clocks.html))?

This project stubs the getUser method of oidc-client's UserManager class in some of it's unit tests. I like this approach more than exposing methods to fake authentication state in the plugin code. An example with a test like this (though this is a mocha test, sinon is used for the stubbing – I guess in Cypress you would write `cy.stub()` in stead of `sinonSandbox.stub()`).

**Comment by larzon83** [comment]
thx for your input. I've found a way to trick my app to always think it's logged in:
- I generated a long lived token by setting `SSO Session Idle` in keycloak to 3000 days -> valid till 2028
- Logged into my dev app that I use for e2e testing and grabbed the whole `oidc.user ...` object from localStorage and putted it into a js file like so:
```js
// cypress/fixtures/token.js

module.exports = {
	// only id_token is needed, access_token etc can be omitted
	id_token: 'your-id_token-string',
 	// profile is needed for my app to greet the user
	profile: {
		name: 'John',
		preferred_username: 'john',
		given_name: 'John'
	}
}
```
- Then I added a `window:before:load` hook in the cypress commands file:
```js
// cypress/support/commands.js

Cypress.on('window:before:load', win => {
	// Override Cypress' clearing of localStorage between tests
	// https://github.com/cypress-io/cypress/issues/461#issuecomment-520132801
	Cypress.LocalStorage.clear = function (keys, ls, rs) {}

	const token = require('./../fixtures/token')
	// set an object into localStorage like vuex-oidc wants it to be
	win.localStorage.setItem(
		'oidc.user:http://localhost:8080/auth/realms/REALM_NAME:CLIENT_NAME',
		JSON.stringify(token)
	)
})
```
- Now, before each `cy.visit()` the token is put into localStorage and when the app loads, vuex-oidc thinks, it has a valid token 😄

**Comment by perarnborg** [comment]
Thank you for sharing @larzon83. 

I’ll close this for now, please reopen if you want to discuss this some more.
