### ISSUE TITLE
How can pass id_token_hint to signoutRedirect method

### ISSUE THREAD

**Issue by zredb** [perarnborg/vuex-oidc#73]
Hello，
     If I want to bypass the logout prompt, I need to pass id_token_hint parameter to end session endpoint, but now it seems no way to pass this parammeter using signoutRedirect method.  because the signOutOidc: function signOutOidc(context) method only has one parameter context which corresponding to store. how can I pass id_token_hint to signoutRedirect method? thank you！

**Comment by perarnborg** [comment]
As of v3.4.0 you can dispatch signOutOidc({ id_token_hint: 'hint' }).
