### ISSUE TITLE
AuthenticateOidc dispatch action question

### ISSUE THREAD

**Issue by SoroTrestal** [perarnborg/vuex-oidc#76]
Hello, is there any example code how to use the authenticateOidc dispatch action, I want to authenticate before my app gets loaded.

Right now i'm stuck in a redirect loop, if I use it.

Kind regards

_Originally posted by @SoroTrestal in https://github.com/perarnborg/vuex-oidc/issues/60#issuecomment-579714786_

**Comment by razvanreb** [comment]
https://github.com/perarnborg/vuex-oidc-example/blob/master/src/App.vue#L31

Have a try on this example, using `authenticateOidc `instead of `authenticateOidcPopup`.
