### ISSUE TITLE
Update wiki to include filenames

### ISSUE THREAD

**Issue by tommed** [perarnborg/vuex-oidc#8]
Great project, looking forward to using it.

From someone looking at it clean though, I think the wiki documentation would be a lot easier to follow if you provided the filenames of each code example above them?

Obviously Vue.Js is quite flexible about storing files, but just getting something working from scratch - it would be nice to follow exactly your working version, then change it to fit the project and developer preferences?

I'm assuming from a later import that the first example with oidc settings is stored to the root vuejs folder with the filename `config.js`, but the rest I haven't figured out yet.

**Comment by perarnborg** [comment]
Right, I have tried to keep everything not opinionated, so file structure is not anything that realt matters. 

But one thing I imagine would be helpful is to have a complete example implementation for refererence. I will provide that and refer to it in the docs, thanks for the input!

**Comment by perarnborg** [comment]
The wiki now has links to an example setup project. The documentation could be improved further obviously, help and suggestions are welcome!
