### ISSUE TITLE
[Question] Data not consumed after login

### ISSUE THREAD

**Issue by Henreich** [perarnborg/vuex-oidc#80]
Hello, Ive been trying out the example application and it works just fine with the google login example, however it stops working when I replace the oidcSettings with my own. 
I am directed to the login page correctly, but when I am redirected after login all the data is in the URL and the vuex state doesnt update with the information. The URL looks like this:

`https://localhost:3000/#access_token=MY_ACCESS_TOKEN&scope=MY_SCOPE&id_token=MY_ID_TOKEN&state=STATE&token_type=Bearer&expires_in=28799`

Heres what I can show of my oidcSettings: 

```
export const oidcSettings = {
    authority: 'AUTH_LINK',
    clientId: 'CLIENT_ID',
    redirectUri: 'https://localhost:3000/',
    postLogoutRedirectUri: 'https://localhost:3000/logout',
    responseType: 'id_token token',
    scope: 'openid customprofile',
    loadUserInfo: false,
};
```

Any idea what might be wrong?

**Comment by perarnborg** [comment]
Your app needs to handle the callback from the identity provider. In your example you have entered https://localhost:3000/ as redirectUri. If you are using the code from the example application, the callback is handled on the route /oidc-callback (you should dispatch the action oidcSignInCallback on the route that the provider sends you to, like in https://github.com/perarnborg/vuex-oidc-example/blob/master/src/views/OidcCallback.vue).

I hope this can help you!
