### ISSUE TITLE
After succesful login and opening redirectPath, upon F5 router loads oidc callback url resulting in oidc callback error

### ISSUE THREAD

**Issue by ux-engineer** [perarnborg/vuex-oidc#81]
I have a custom modified version of your router beforeEach guard:

```js
const authGuard: NavigationGuard = async (to, from, next) => {
  // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
  const store = require('@/store').useStore();
  // Handle these routes in their dedicated callback handlers or otherwise handled
  const routeNamesWithCallbackHandlers = ['oidcCallback', 'sessionExpired'];
  if (to.name && routeNamesWithCallbackHandlers.includes(to.name)) {
    next();
  }
  try {
    const hasAccess: boolean = await store.dispatch('oidc/oidcCheckAccess', to);
    if (hasAccess) {
      if (to.name === 'login') {
        next({ name: 'home', replace: true });
      }
      next();
    }
    // Error handling
  } catch (error) {
    // Reset stores
    store.dispatch('reset');
  }
};
```

And having Oidc Callback logic in a function that is passed as a callback function to my oidcCallback view from router level (having all the auth logics in a single guards file, destructure-imported to router, as hinted in my previous issue/question: https://github.com/perarnborg/vuex-oidc/issues/77

```js
const handleOidcCallback = async function handleOidcCallbackFn(context: SetupContext) {
  try {
    // Dispatch oidcSignInCallback store action
    const redirectPath: string = await context.root.$store.dispatch('oidc/oidcSignInCallback');
    // Redirect to configured path
    context.root.$router.replace(redirectPath);
    // Error handling
  } catch (error) {
    // Redirect to an error page...should perhaps be a common error page
    context.root.$router.replace({ name: 'oidcCallbackError' });
  }
};
```

As a question and a future reference to others, possibly encountering similar problems, here's what I uncovered.

When after a successful login flow I'm redirected to `redirectPath`. If I then refresh the page, the address bar still has oidc-callback address with the query string parameters.

Which results in `oidc-client-js` library triggering an error:

> Error in handleOidcCallback - dispatch oidcSignInCallback - error - route to oidcCallbackError  Error: "No matching state found in storage" 

Which then redirects to Oidc Callback Error view...

Do you know why Vue Router updates that old address after refresh, even when I'm using the replace method?

**Comment by perarnborg** [comment]
@ux-engineer Just wanted to say that I am sorry I have not found the time yet to look at this.

**Comment by perarnborg** [comment]
@ux-engineer Is this still an issue for you? I can't see that this library should be doing anything that messes with vue-routers api.

**Comment by ux-engineer** [comment]
@perarnborg I'm working on a new app and have ported previous version of vuex-oidc implementation there. So far things have been working better, as with the previous project there was some edge cases, especially one case noticeable with Firefox (related to History API it seemed, working somehow differently as used by vue-router).

It seems these lately done fixes to this library may have fixed those scenarios. I will continue debugging and polishing this auth guard approach as we are soon to upgrade to  Vue 3.0.

One thing I may open a feature request for, as I've implemented this custom auth guard, I may need to have "isCallbackRoute" method exposed from the Vuex module... Because when oidcCallback route is called again after redirecting back from the auth uri, I need to discern if this route call was like that, and route to default page or previously used page.

Currently the guard looks like this:
```

const authGuard: NavigationGuard = async (to, from, next) => {
  // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
  const store = require('@/store').useStore();

  console.debug(`authGuard > from ${from.path}, to ${to.path}:`, from, to);

  try {
    const hasAccess: boolean = await store.dispatch('oidc/oidcCheckAccess', to);
    // TODO: Issue feature request for exposing isCallback action
    const isOidcCallbackRoute = to.path === '/oidc-callback';

    if (isOidcCallbackRoute && hasAccess) {
      const path = sessionStorage.getItem('vuex_oidc_active_route') || '/';
      console.debug(`authGuard > hasAccess: ${hasAccess}, isOidcCallbackRoute: ${isOidcCallbackRoute} > Route to path: ${path}`);
      next(path);
      return;
    }
    if (hasAccess) {
      console.debug(`authGuard > hasAccess: ${hasAccess}, isOidcCallbackRoute: ${isOidcCallbackRoute} > next...`);
      next();
      return;
    }
    console.debug(`authGuard > hasAccess: ${hasAccess}, isOidcCallbackRoute: ${isOidcCallbackRoute} > No access to next (empty return)`);
    return;

  // Error handling
  } catch (error) {
    // Reset stores and log error ...
  }
};
```

**Comment by perarnborg** [comment]
OK, sounds good! I will close this issue for now, feel free to open again if you wish.
