### ISSUE TITLE
Thank you，Your project is nice；but,I have a few questions

### ISSUE THREAD

**Issue by zhk0603** [perarnborg/vuex-oidc#84]
1: why not implemented: "signoutPopup"
2: How to get "UserManager" instance externally

**Comment by perarnborg** [comment]
I think both of your feature requests are valid, and I can see the point of both of them.

Currently there is no way to ger the user manager instance, but I will look in to a way to expose it.

**Comment by perarnborg** [comment]
@zhk0603 signoutPopup was published in v3.4.2
