### ISSUE TITLE
Setting specific routes as public doesn't work with Nuxt

### ISSUE THREAD

**Issue by volvotrax** [perarnborg/vuex-oidc#87]
Hello,
First of all, thank you for all your useful work.

## Problem
When using Nuxt, setting meta.isPublic on a page doesn't work: isPublic is ignored and the route require authentication.

_Example:_
```
// pages/index.vue
export default {
  name: 'Index',
  layout: 'main',
  meta: {
    isPublic: true
  },
/*....*/
```

## Suggested Solution
It doesn't work because route.meta is an array. Therefore `route.meta && route.meta.isPublic` returns false.

https://github.com/perarnborg/vuex-oidc/blob/0b4c1aeb6f7661ffde8d96e59f65afd948bfb95e/src/store/create-store-module.js#L67-L70

A possible fix could be:
```
    if (route.meta) {
      if (Array.isArray(route.meta) && route.meta[0] && route.meta[0].isPublic) {
        return true;
      } else if (route.meta.isPublic) {
        return true; 
      }
    }
```
Let me know if you wish I open a PR.

## Note
storeSettings.isPublicRoute is ignored when publicRoutePaths is set.
Maybe you could update the wiki with this information. :)

Thank you!

**Comment by perarnborg** [comment]
Good point. I noticed this when I first implemented nuxt support, and I felt a little uneasy about how exactle the array in nuxt is composed. Is it good enough to check if meta is an array and in that case look at the first item in the array?

I opted to instead add a setting for the vuex store module called `publicRoutePaths ` that can be used in stead of the route meta. See https://github.com/perarnborg/vuex-oidc/wiki#2-setup-vuex in the docs and the example at https://github.com/perarnborg/vuex-oidc-example-nuxt/blob/master/store/oidc.js#L19

Maybe we should support the meta array as well, what are your thoughts?

**Comment by Chuck-Work-Bots** [comment]
Hello @perarnborg ,

`publicRoutePaths` doesn't appear to be working in Nuxt with dynamic routes with slugs, so it isn't a full solution.

To handle the meta array, the Nuxt docs use the latest route child:

https://github.com/nuxt/nuxt.js/blob/b83b5675043ebdfec3398bd83fd27dfe77cdd620/examples/routes-meta/middleware/theme.js#L1-L4

So `if (route.meta && route.meta.reduce((isPublic, meta) => meta.isPublic || isPublic, false)) {` might be more consistent with their styling and provide more granular control over routes.

I'd love to see this implemented - let me know if I should submit a PR.

Thank you

```

**Comment by perarnborg** [comment]
Thanks @Chuck-Work-Bots for the example of a "nuxt way" to check the meta.

**Comment by perarnborg** [comment]
@volvotrax Sorry that this took so long. I will fix the behaviour of storeSettings.isPublicRoute being ignored when publicRoutePaths is set, it feels like that was a bug.

**Comment by perarnborg** [comment]
As of v3.10.0 this should be fixed.
