### ISSUE TITLE
vuexOidcProcessSilentSignInCallback with config

### ISSUE THREAD

**Issue by bcronje** [perarnborg/vuex-oidc#88]
The wiki and demo app currently states you need the following code to do silent signin:

```
import { vuexOidcProcessSilentSignInCallback } from 'vuex-oidc'
import { oidcSettings } from '@/config'

vuexOidcProcessSilentSignInCallback(oidcSettings)
```

However `vuexOidcProcessSilentSignInCallback` is essentially `processSilentSignInCallback ` and it does not take an [argument](https://github.com/perarnborg/vuex-oidc/blob/master/src/services/oidc-helpers.js#L81).

Is this a documentation issue, or a bug in `processSilentSignInCallback` ?

PS I hope you merge https://github.com/perarnborg/vuex-oidc/pull/79 as this issue was picked up automatically by Typescript after I manually added the typings from that PR.

**Comment by perarnborg** [comment]
You are correct, there was a mistake in the docs. Fixed now, thank you!

I want to merge the typings PR, but will have to take some time to look at them one last time. Will hopefully do this within short.
