### ISSUE TITLE
User not redirecting to IS4 when token is expired

### ISSUE THREAD

**Issue by SoroTrestal** [perarnborg/vuex-oidc#9]
Hello, in the original sample of oidc when you remove the entry from the local storage.
The sample would redirect you to IS  is this also possible with your implementation?

Also when my session does expire,i have to manualy refresh my page to let it redirect to IS.

Or am I doing something wrong?

Thank you.

**Comment by perarnborg** [comment]
@SoroTrestal You have to setup automatic silent renew to get the behaviour where the token is renewed before it expires. 

https://github.com/perarnborg/vuex-oidc/wiki#9-optional-setup-silent-renew-callback

Perhaps it could be the nice to redirect the user to authentication if the token expires on a non public route. However I do not feel certain that this is a behavior that everyone would want. So I would rather implement some kind of interface that enables you to optionally do that.

I am not sure that I understand your first question about removing the entry from local storage. What is the scenario where you would want to do that?

**Comment by perarnborg** [comment]
@SoroTrestal could you elaborate on what you mean when you say the original sample of oidc and the issue where you remove the entry from local storage?

**Comment by SoroTrestal** [comment]
> Perhaps it could be the nice to redirect the user to authentication if the token expires on a non public route. However I do not feel certain that this is a behavior that everyone would want. So I would rather implement some kind of interface that enables you to optionally do that.

This would be handy indeed, right now I can keep switching routes. 

I meant if a user would clear his browser cache (for some reason), or manually remove the item from the localStorage, I was trying to simulate this.
In the original sample there's allready some sort of mechanism that polls the token and redirects you (or if you would visit a different route that requires authentication).

**Comment by perarnborg** [comment]
You can try v1.9.0 where a check of token expiration is added. 

Just one thing: what are you referring to when you say "the original sample"?

**Comment by SoroTrestal** [comment]
> You can try v1.9.0 where a check of token expiration is added.
> 
> Just one thing: what are you referring to when you say "the original sample"?

From the oidc wiki there's a link to a vue.js implementation [test project](https://github.com/joaojosefilho/vuejsOidcClient)

**Comment by perarnborg** [comment]
@SoroTrestal There is an example of a setup with automatic silent renew in https://github.com/perarnborg/vuex-oidc-example

Right now the vuex-oidc getters will check if the tokens expiry time has exeeded and will return null (and oidcIsAuthenticated will be false), but there is no continuous interval check of the token, you can always set that up yourself in your app.

oidc-client, which vuex-oidc (and the sample implementation you are referring to) are built upon, has an event interface that I have chosen to not expose in vuex-oidc. I might have a look at that in the future. However if you manage to setup silent renew you hopefully do not need to listen for any events imperatively in your app.

**Comment by SoroTrestal** [comment]
> @SoroTrestal There is an example of a setup with automatic silent renew in https://github.com/perarnborg/vuex-oidc-example
> 
> Right now the vuex-oidc getters will check if the tokens expiry time has exeeded and will return null (and oidcIsAuthenticated will be false), but there is no continuous interval check of the token, you can always set that up yourself in your app.
> 
> oidc-client, which vuex-oidc (and the sample implementation you are referring to) are built upon, has an event interface that I have chosen to not expose in vuex-oidc. I might have a look at that in the future. However if you manage to setup silent renew you hopefully do not need to listen for any events imperatively in your app.

@perarnborg, Ok thank you very much, I will check it out.

**Comment by SoroTrestal** [comment]
@perarnborg Sweet feature, thanks. one other thing I noticed is that oidcIsAuthenticated never gets set to false (the exp date is always Sun Jan 18 1970 20:56:07), perhaps I'm missing some setting in IS.

**Comment by perarnborg** [comment]
That sounds strange. Would you care to share some code?

**Comment by perarnborg** [comment]
@SoroTrestal I would advise you to update to the latest version of vuex-oidc (v1.10.4) – I have made a few improvements of both automatic silent renew and of the expiration check.

One thing regarding the automatic silent renew: if you want to test it with very short expiration times (to be specific that is times of 60 seconds or less) you need to configure the oidc setting accessTokenExpiringNotificationTime to a value lower than your tokens time to live (see oidc-client docs: https://github.com/IdentityModel/oidc-client-js/wiki#other-optional-settings). This is the number of seconds before your tokens expire that the client will try to reauthenticate – the default value is 60.

**Comment by perarnborg** [comment]
@SoroTrestal I'm sorry, make that v1.10.5

**Comment by SoroTrestal** [comment]
> @SoroTrestal I'm sorry, make that v1.10.5

Ok thanks I will try it out, I had indeed set the expiration at 60 seconds.

I think there is no problem, I was confused when I placed some logging in your code:

> vuex-oidc.esm.js

```
var tokenExp = function tokenExp(token) {
  if (token) {
    console.log("tokenExp", new Date(parseJwt(token).exp));
    var parsed = parseJwt(token);
    return parsed.exp ? parsed.exp * 1000 : null;
  }
  return null;
};
```

> logs: tokenExp Sun Jan 18 1970 21:01:42 GMT+0100 (Midden-Europese standaardtijd)

```
var tokenIsExpired = function tokenIsExpired(token) {
  var tokenExpiryTime = tokenExp(token);
  console.log({ "tokenIsExpired": new Date(tokenExpiryTime) });
  if (tokenExpiryTime) {
    return tokenExpiryTime < new Date().getTime();
  }
  return false;
};
```

> logs: Object
> tokenIsExpired: Tue Oct 30 2018 13:35:09 GMT+0100 (Midden-Europese standaardtijd)
> __proto__: Object
> __proto__: Object

So the exp date changes correctly.

I have this set up for my client in IS:

```
new Client {
                    ClientId = "testvueclientjs",
                    ClientName = "testvueclientjs",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    AccessTokenType = AccessTokenType.Jwt,
                    //UpdateAccessTokenClaimsOnRefresh = true,
                    AllowOfflineAccess = true,
                    //Access token life time is 7200 seconds (2 hour)
                    //AuthorizationCodeLifetime = 15,
                    //IdentityTokenLifetime = 15,
                    //AccessTokenLifetime = 15,
                    IdentityTokenLifetime = 7200,                    
                    UpdateAccessTokenClaimsOnRefresh = true,                    
                    AlwaysSendClientClaims = true,
                    AccessTokenLifetime = 7200,                  
                    RequireConsent = false,
                    RedirectUris = new List<string>
                    {
                        "http://localhost:8080/callback/",
                        "http://localhost:8080/callback",
                        "http://localhost:8080/#/callback/#",
                        "http://localhost:8080/auth/signinwin/main",
                        "http://localhost:8080/oidc-callback",
                        "http://localhost:8080/static/callback.html",
                        "http://localhost:8080/public/callback.html",
                        "http://localhost:8080/silent-renew-oidc.html"
                    }
                    ,
                    PostLogoutRedirectUris = new List<string>
                    {
                        "http://localhost:8080/"
                    },                  
                    AllowedCorsOrigins =     { "http://localhost:8080/"},
                    //
                    AllowedScopes = {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "TestApi", "api", "authorisation_api",
                        IdentityServerConstants.StandardScopes.OfflineAccess
                    }
                    //
                    //AlwaysIncludeUserClaimsInIdToken=true
                }
```

And in the config.js:

```
export const oidcSettings = {  
    authority: 'http://localhost/Geoit.IdentityServer',
    client_id: 'testvueclientjs',
    redirect_uri: 'http://localhost:8080/oidc-callback',
    response_type: 'id_token token',
    scope: 'openid profile TestApi api offline_access',
    automaticSilentRenew: true,
    silent_redirect_uri: 'http://localhost:8080/silent-renew-oidc.html'
  }
```

Thanks for the changes.

**Comment by perarnborg** [comment]
@SoroTrestal Do I understand correctly that everything is working as expected now?

**Comment by SoroTrestal** [comment]
@perarnborg Yes, thanks again for the changes.

I'm still finding a clean solution to set my users roles and permissions.
For now I have implemented the events like this:

The will be a cleaner solutions ofc.

```
modules: {
    oidcStore: vuexOidcCreateStoreModule(oidcSettings, {
      namespaced: true
    }, {
      userLoaded: (user) => {
        console.log("USER LOGGED IN:", user);
        axios.defaults.headers.common["Authorization"] = `Bearer ${  
             user.access_token ? user.access_token : ""}`;
        //
        if (user) {
          const service = new SecurityService();
          service.getUserRoles().then(roles => {
            console.log("USER ROLES:", roles);
            arguments[1].default.commit('setUserRoles', roles);            
          });
        }
      },
      accessTokenExpired: () => {
        window.location.reload();
      },
      userSignedOut: () => {
        window.location.reload();
      }
    })
  }
```

**Comment by perarnborg** [comment]
I am not sure that I understand your code correctly. Does SecurityService.getUserRoles fetch the roles from another source than the signin authority? 

If the roles exist as claims on the signin authority one option is the load them in the token by authenticating with a scope that collects the roles claim.

Otherwise there is an option to listen for browser events from vuex-oidc instead (if you are depeloping a web app that is). I have added documentation for this in https://github.com/perarnborg/vuex-oidc/wiki#10-optional-setup-oidc-client-event-listeners . Basically what you would do would be  window.addEventListener('vuexoidc:userLoaded', () => {}) which means you are less limitted in where you place your code.

**Comment by perarnborg** [comment]
@SoroTrestal I realized the docs where inclomplete on the window events, you need to pass a setting `dispatchEventsOnWindow: true` when you create the vuex module to have the events on window. Docs are updated.
