### ISSUE TITLE
how to setup silent renew callback

### ISSUE THREAD

**Issue by hhuseyinpay** [perarnborg/vuex-oidc#90]
Hi, first of all, thank you very much for developing this library! My setup is:
config.js:
![Screen Shot 2020-04-03 at 23 58 05](https://user-images.githubusercontent.com/14811488/78404737-b0b93d80-7607-11ea-9e13-1fdad0d06d87.png)

route.js:
![Screen Shot 2020-04-04 at 00 03 57](https://user-images.githubusercontent.com/14811488/78404796-cb8bb200-7607-11ea-9809-8cc51d9ccb2e.png)

SlientSigninCallback.vue:
![Screen Shot 2020-04-04 at 00 04 12](https://user-images.githubusercontent.com/14811488/78404809-d47c8380-7607-11ea-9a17-a7581d64745f.png)

Startup.cs:
![Screen Shot 2020-04-04 at 00 05 11](https://user-images.githubusercontent.com/14811488/78404889-0261c800-7608-11ea-9388-7b221d5ad09d.png)

 When the token is expired following error occurs
![Screen Shot 2020-04-04 at 00 58 33](https://user-images.githubusercontent.com/14811488/78408856-df87e180-7610-11ea-84e2-f4cfd0831659.png)

**Comment by birula** [comment]
Hi @hhuseyinpay make sure the silentRedirectUri is present in the IdentityServer RedirectUris.

**Comment by hhuseyinpay** [comment]
Thank you for your reply. I solved the issue with the following setup:

![Screen Shot 2020-04-04 at 19 17 39](https://user-images.githubusercontent.com/14811488/78455830-27f2de00-76a9-11ea-8f5e-b8ab51b42a8f.png)

I'm a newbie at IdentityServer, so is this setup correct? Is there any better way to configure IdentityServer?

**Comment by birula** [comment]
i'm still learning IdentityServer too, i have followed [this article](https://www.scottbrady91.com/Identity-Server/Getting-Started-with-IdentityServer-4) to create my initial configuration.

Hope it helps.
