### ISSUE TITLE
在用户未登录时调用getOidcUser会报错

### ISSUE THREAD

**Issue by cocomilk2012** [perarnborg/vuex-oidc#99]
getOidcUser: function getOidcUser(context) {
      /* istanbul ignore next */
      return oidcUserManager.getUser().then(function (user) {
        if (user) {//添加null判断
          context.commit('setOidcUser', user);
        }
        return user;
      });
    },
这里需要添加判断是否null

**Comment by perarnborg** [comment]
I am not sure I understand. What would you like to happen if the user is `null`?

**Comment by perarnborg** [comment]
Fixed as of v3.5.2, if I understand this correctly.
